//@version=6
indicator("Bollinger Bands", shorttitle = "BB", overlay = true)
import michaelpbgilbride/MPBGTradingLibrary/1 as mpbg

length = input.int(20, "Length", step = 1, minval = 1)
maType = input.string("SMA", "Basis MA Type", options = ["SMA", "EMA", "RMA", "WMA", "VWMA"])
src = input(close, "Source")
mult = input.float(2.0, "Std Dev", step = 0.25, minval = 0.001, maxval = 50)
bandColor = input.color(color.rgb(240, 175, 142), "Colour")
fillColor = input.color(color.rgb(240, 175, 142, 96), "Background")
[basis, upper, lower] = mpbg.bollinger(src, length, mult, maType)
plot(basis, "Basis", color = bandColor, style = plot.style_circles)
p1 = plot(upper, "Upper", color = bandColor, style = plot.style_circles)
p2 = plot(lower, "Lower", color = bandColor, style = plot.style_circles)
fill(p1, p2, color = fillColor)
