//@version=6
indicator("QMP Filter", shorttitle = "QMP", overlay = true)
import michaelpbgilbride/MPBGTradingLibrary/1 as mpbg

sourceMACD = input.source(close, "MACD Source", group = "Sources")
sourceQQE = input.source(close, "QQE Source", group = "Sources")
maTypeMACD = input.string("DEMA", "MACD Smoothing", options = ["EMA", "DEMA", "TEMA", "HMA", "EHMA", "Zero-Lag Weak", "SuperSmoother"], group = "Sources")
maTypeQQE = input.string("EMA", "QQE Smoothing", options = ["EMA", "DEMA", "TEMA", "HMA", "EHMA", "Zero-Lag Weak", "SuperSmoother"], group = "Sources")
rsiTypeQQE = input.string("RSI", "QQE RSI Type", options = ["RSI", "Stochastic RSI", "Ehlers' RSIH"], group = "Sources")
stochRsiLength = input.int(14, "Stochastic RSI Length", minval = 1, group = "Sources")
stochRsiSmooth = input.int(3, "Stochastic RSI Smoothing", minval = 1, group = "Sources")
fastLength = input.int(12, "MACD Fast", step = 1, group = "MACD")
slowLength = input.int(26, "MACD Slow", step = 1, group = "MACD")
smoothInput = input.int(9, "MACD Smooth", step = 1, group = "MACD")
[macdLine, signalLine, _] = mpbg.macd(sourceMACD, fastLength, slowLength, smoothInput, maTypeMACD)

rsiPeriod = input.int(8, "RSI Period", step = 1, group = "QQE")
sf = input.int(1, "SF", step = 1, group = "QQE")
wp = input.float(3.0, "WP", step = 0.25, group = "QQE")
[upSwitch, downSwitch] = mpbg.qqeQmpSignalsAdvanced(sourceQQE, rsiPeriod, sf, wp, maTypeQQE, rsiTypeQQE, stochRsiLength, stochRsiSmooth, macdLine, signalLine)
plotchar(upSwitch, char = "*", color = color.rgb(51, 204, 225), size = size.small, location = location.belowbar, title = "Buy Signal")
plotchar(downSwitch, char = "*", color = color.rgb(237, 220, 89), size = size.small, location = location.abovebar, title = "Sell Signal")
alertcondition(upSwitch, title = "QMP Buy", message = "BUY")
alertcondition(downSwitch, title = "QMP Sell", message = "SELL")
