//@version=6
indicator("QQE Advanced", shorttitle = "QQE Adv", overlay = false)
import michaelpbgilbride/MPBGTradingLibrary/1 as mpbg

rsiPeriod = input.int(10, "RSI Period", step = 1, group = "QQE Settings")
sf = input.int(14, "SF", step = 1, group = "QQE Settings")
wp = input.float(2.0, "WP", step = 0.025, group = "QQE Settings")
sourceQQE = input.source(close, "Source", group = "QQE Settings")
maTypeQQE = input.string("EMA", "Smoothing Function",
     options = ["EMA", "DEMA", "TEMA", "HMA", "EHMA", "Zero-Lag Weak", "SuperSmoother"],
     group = "QQE Settings")
[rsiMa, trailingLine] = mpbg.qqeLines(sourceQQE, rsiPeriod, sf, wp, maTypeQQE, "RSI")
plot(rsiMa, color = color.new(color.purple, 0), linewidth = 1, title = "QQE RSI MA")
plot(trailingLine, color = color.new(color.green, 0), linewidth = 2, title = "QQE 2nd RSI")
hline(65, color = color.gray, title = "QQE Top Level")
hline(50, color = color.new(color.gray, 30), title = "QQE Centre Level")
hline(35, color = color.gray, title = "QQE Bottom Level")
