//@version=6
indicator("Synthetic Oscillator", shorttitle = "SO", overlay = false)
import michaelpbgilbride/MPBGTradingLibrary/1 as mpbg

src = input.source(close, "Source")
lb = input.int(15, "Lower Bound", minval = 3)
ub = input.int(25, "Upper Bound", minval = 4)
if lb >= ub
    runtime.error("The 'Upper Bound' value must be greater than the 'Lower Bound' value.")
so = mpbg.syntheticOscillator(src, lb, ub)
plot(so, "Synthetic Oscillator")
hline(0, "Zero Line")
